
import React from 'react';

export const TRANSLATIONS = {
  en: {
    brand: "Sadaqah",
    navHome: "Home",
    navDonate: "Donate",
    navUpdates: "Updates",
    navAbout: "About",
    heroTitle: "Before Ramadan, Your $1 Can Bring Hope",
    heroSubtitle: "Thousands of families are struggling to prepare for Ramadan. You don’t need to be rich to help—just $1 can make a difference.",
    ctaDonate: "Donate $1 Now",
    ctaHelp: "Help a Family Today",
    countdownTitle: "Time left until Ramadan",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    statsRaised: "Total Raised (USD)",
    statsDonors: "Generous Donors",
    statsFamilies: "Families Supported",
    impactTitle: "Choose Your Donation",
    impactSubtitle: "Every dollar counts towards feeding a family in need.",
    customAmount: "Custom Amount",
    donateNow: "Complete Donation",
    transparencyTitle: "Transparency First",
    transparencySubtitle: "Your trust is our most valuable asset. Here is how we work.",
    transparency1: "Regular updates and receipts",
    transparency2: "Respectful distribution",
    transparency3: "Your donation goes directly to families",
    footerAbout: "Our mission is simple: to prove that collective small actions can change lives. One dollar at a time.",
    footerLinks: "Quick Links",
    footerLegal: "Legal",
    footerCopyright: "© 2026 Sadaqah | All rights reserved.",
    usdtTitle: "USDT Crypto Payment",
    usdtInstructions: "Send USDT (TRC20 or ERC20) to the address below, then enter your transaction hash.",
    txHashPlaceholder: "Enter Transaction Hash",
    submitHash: "Confirm Payment",
    thankYou: "May your generosity be rewarded!",
    pendingVerification: "Pending verification...",
    updatesComingSoon: "Coming soon in Ramadan, updates will be published daily.",
    privacyTitle: "Privacy Policy",
    privacyIntro: "We value your privacy and are committed to protecting your personal data.",
    privacySection2Title: "2. How We Use Information",
    privacySection2Body: "We use the information we collect for the following purposes: Securely processing donations, improving the user experience on the site, sending notifications or updates related to the initiative (upon consent), enhancing transparency and reporting on donations, and protecting the site from fraud or illegal use.",
    privacySection3Title: "3. Data Protection",
    privacySection3Body: "We are committed to taking all appropriate technical and administrative measures to protect user data, including: Using encrypted security protocols (SSL), relying on trusted and secure payment gateways, and restricting access to sensitive data.",
    privacySection4Title: "4. Sharing Information with Third Parties",
    privacySection4Body: "We do not sell or share your personal data with any third party, except in the following cases: Payment service providers (such as PayPal and Stripe) to process donations, and legal authorities if requested in accordance with the law.",
    privacySection5Title: "5. Cookies",
    privacySection5Body: "Sadaqah may use cookies to improve user experience, such as: Saving preferred language and analyzing site usage to improve performance. You can disable cookies from your browser settings at any time.",
    privacySection6Title: "6. User Rights",
    privacySection6Body: "You have the right to: Request to know the data we hold about you, request modification or deletion of your personal data, and contact us for any privacy-related inquiry.",
    privacySection7Title: "7. Donation Policy",
    privacySection7Body: "All donations made through the Sadaqah website are used to support needy families and charitable projects as described on the site. We are committed to transparency in displaying results and reports.",
    privacySection8Title: "8. Amendments to Privacy Policy",
    privacySection8Body: "We may update the privacy policy from time to time, and any amendments will be posted on this page.",
    privacySection9Title: "9. Contact Us",
    privacySection9Body: "If you have any inquiries regarding the privacy policy, you can contact us via:",
    privacyEmail: "sadaqah20266@gmail.com"
  },
  ar: {
    brand: "صدقة | Sadaqah",
    navHome: "الرئيسية",
    navDonate: "تبرع الآن",
    navUpdates: "التحديثات",
    navAbout: "عن المبادرة",
    heroTitle: "قبل رمضان… دولار واحد منك يصنع أملًا",
    heroSubtitle: "عائلات كثيرة لا تملك ما يكفي لاستقبال رمضان. لست بحاجة لأن تكون غنيًا—تبرع ولو بدولار واحد.",
    ctaDonate: "تبرع بدولار واحد الآن",
    ctaHelp: "ساعد أسرة اليوم",
    countdownTitle: "الوقت المتبقي لرمضان 2026",
    days: "أيام",
    hours: "ساعات",
    minutes: "دقائق",
    seconds: "ثواني",
    statsRaised: "إجمالي التبرعات (دولار)",
    statsDonors: "عدد المتبرعين",
    statsFamilies: "عائلات تم دعمها",
    impactTitle: "اختر تبرعك",
    impactSubtitle: "كل دولار يساهم في إطعام أسرة محتاجة.",
    customAmount: "مبلغ مخصص",
    donateNow: "إتمام التبرع",
    transparencyTitle: "الشفافية أولاً",
    transparencySubtitle: "ثقتكم هي أغلى ما نملك. إليكم كيف نعمل.",
    transparency1: "تحديثات وتقارير دورية",
    transparency2: "توزيع باحترام وكرامة",
    transparency3: "تبرعك يصل مباشرة للمحتاجين",
    footerAbout: "مهمتنا بسيطة: إثبات أن الأفعال الصغيرة الجماعية يمكن أن تغير حياة الناس. دولار واحد في كل مرة.",
    footerLinks: "روابط سريعة",
    footerLegal: "قانوني",
    footerCopyright: "© 2026 Sadaqah | All rights reserved.",
    usdtTitle: "الدفع بالعملات المشفرة USDT",
    usdtInstructions: "أرسل USDT (TRC20 أو ERC20) إلى العنوان أدناه، ثم أدخل رقم العملية.",
    txHashPlaceholder: "أدخل رقم العملية (Tx Hash)",
    submitHash: "تأكيد الدفع",
    thankYou: "جزاكم الله خيراً على كرمكم!",
    pendingVerification: "في انتظار التحقق...",
    updatesComingSoon: "قريباً في رمضان سيتم نشر التحديثات يومياً.",
    privacyTitle: "سياسة الخصوصية",
    privacyIntro: "نحن نقدر خصوصيتك ونلتزم بحماية بياناتك الشخصية.",
    privacySection2Title: "2️⃣ كيفية استخدام المعلومات",
    privacySection2Body: "نستخدم المعلومات التي نجمعها للأغراض التالية: معالجة التبرعات بشكل آمن، تحسين تجربة المستخدم في الموقع، إرسال إشعارات أو تحديثات متعلقة بالمبادرة (عند الموافقة)، تعزيز الشفافية وإعداد تقارير عن التبرعات، وحماية الموقع من الاحتيال أو الاستخدام غير القانوني.",
    privacySection3Title: "3️⃣ حماية البيانات",
    privacySection3Body: "نلتزم باتخاذ جميع الإجراءات التقنية والإدارية المناسبة لحماية بيانات المستخدمين، بما في ذلك: استخدام بروتوكولات أمان مشفرة (SSL)، الاعتماد على بوابات دفع موثوقة وآمنة، وتقييد الوصول إلى البيانات الحساسة.",
    privacySection4Title: "4️⃣ مشاركة المعلومات مع أطراف ثالثة",
    privacySection4Body: "نحن لا نبيع أو نشارك بياناتك الشخصية مع أي جهة خارجية، باستثناء الحالات التالية: مزودي خدمات الدفع (مثل PayPal وStripe) لمعالجة التبرعات، والجهات القانونية إذا طُلب منا ذلك وفقًا للقانون.",
    privacySection5Title: "5️⃣ ملفات تعريف الارتباط (Cookies)",
    privacySection5Body: "قد يستخدم موقع Sadaqah ملفات تعريف الارتباط لتحسين تجربة المستخدم، مثل: حفظ اللغة المفضلة وتحليل استخدام الموقع لتحسين الأداء. يمكنك تعطيل ملفات تعريف الارتباط من إعدادات المتصفح في أي وقت.",
    privacySection6Title: "6️⃣ حقوق المستخدم",
    privacySection6Body: "لديك الحق في: طلب معرفة البيانات التي نبحث عنها، طلب تعديل أو حذف بياناتك الشخصية، والتواصل معنا لأي استفسار يتعلق بالخصوصية.",
    privacySection7Title: "7️⃣ سياسة التبرعات",
    privacySection7Body: "جميع التبرعات التي تتم عبر موقع Sadaqah تُستخدم لدعم الأسر الفقيرة والمشاريع الخيرية وفقًا لما هو موضح في الموقع، ونلتزم بالشفافية في عرض النتائج والتقارير.",
    privacySection8Title: "8️⃣ التعديلات على سياسة الخصوصية",
    privacySection8Body: "قد نقوم بتحديث سياسة الخصوصية من وقت لآخر، وسيتم نشر أي تعديل على هذه الصفحة.",
    privacySection9Title: "9️⃣ التواصل معنا",
    privacySection9Body: "إذا كان لديك أي استفسار حول سياسة الخصوصية، يمكنك التواصل معنا عبر:",
    privacyEmail: "sadaqah20266@gmail.com"
  }
};

export const INITIAL_STATS = {
  totalRaised: 12450,
  totalDonors: 3200,
  familiesSupported: 150,
  ramadanStartDate: "2026-02-18T00:00:00Z"
};

export const IMPACT_LABELS = [
  { amount: 1, labelEn: "Provide a basic meal", labelAr: "توفير وجبة أساسية" },
  { amount: 3, labelEn: "Support a family iftar", labelAr: "دعم إفطار أسرة" },
  { amount: 5, labelEn: "Help with essential supplies", labelAr: "مستلزمات أساسية" },
  { amount: 10, labelEn: "Support a family for a day", labelAr: "دعم أسرة ليوم كامل" }
];

export const CRYPTO_ADDRESSES = {
  TRC20: "TSQtzJN3bDtn4BN2DGdcGDkXgAYuYKae8w",
  ERC20: "0xe14cbf77944adf603e403bffd264ded54c7dc5fe"
};
